name: "PROJECTO - MISO: SOFTWARE CLOUD G32"
aws:
  AWS_ACCESS_KEY_ID: ASIA3GGSDDLFEUNOXVXZ
  AWS_SECRET_ACCESS_KEY: 56MS43qKO4/snymn2tVco6Ni8Wt7LURh/Ixv0NHT
  AWS_SESSION_TOKEN: FwoGZXIvYXdzEGsaDDK5QMfny+UmZK3eISLLAXIbiZQ4+0zDRc7tbo1YS8PfsmCFPPBFo8IBYu4ZtsuDAr2BPHwD24Km2YMQrZlcZzJLQw1snsGdF8/yGI0gcOQiOnAT2UMMaA0quFPgLbSQZHEStlZZ0cjFfv4kIRz3JtMJihhoGuDqe8GDobL5aTx6u4GHHj7s3F3Hw2zRfhx4lkHtdrFqx/oIadG8dIdghvc3H+xgJtFXbV5F+edXZC5fwLrguCotqJj2wCxba2Trzye0EcJdTDEaFyF+X66UqdWErJsNM315ci35KKzx64wGMi3cCdVUhKLhRwVARF1aanYqwkzej3V6FMtrlIV9kg9vgL2k65mv9c282ql09k4=
  BUCKET_NAME: 'miso-cloud-gr32'
app-config:
  JWT_SECRET_KEY: ncF!vCivBkAm&Qvg
  PROPAGATE_EXCEPTIONS: True
  UPLOAD_FOLDER: uploaded_files
  DOWNLOAD_FOLDER: processed_files
  MAX_CONTENT_LENGTH: 40000000
  CELERY_BROKER_URL: "redis://172.168.1.119:6379/0"
  CELERY_RESULT_BACKEND: "redis://172.168.1.119:6379/0"
smtp:
  SERVER: "172.168.1.252"
  PORT: 1025
  EMAIL: "conversor_miso@conversor.com"
  