name: "PROJECTO - MISO: SOFTWARE CLOUD G32"
aws:
  AWS_ACCESS_KEY_ID: ASIA3GGSDDLFD2VSIKOU
  AWS_SECRET_ACCESS_KEY: WGK248LcwOYPEww633vmghMWDDOiZwJcU4XurVoN
  AWS_SESSION_TOKEN: FwoGZXIvYXdzEH4aDEYDakQVGCKEdPQS8yLLAa9DYf+rBjM7xoMipoVSE0WuewoSlKinxGmjoXmar8GP1xJdJC+6jBhNjSSRJaVwqTYmAnN8zVN+8h64L5E5hqBX+Xvr+7oz6M538ILE808kKElFYfeMsQomT23yChGYLfegJkw2kdynoSBUavoiQiAcaUL2ZEa5RJ1k4dbObLlLFESH+sJXvnyNWww4RaFCgKn1qZbfQTKGKM3Vhe8/2+YzSSA1Gsu8QHjL2udBuYIN6/YSmdMd9bjKeG5qGKZ5frMrIkLjYKIsgToZKOehqI0GMi2o1LHtE8rFtE4AOT42tdtgCEImIEzksnlbBpWaVO2BwxpN79MQXsMfuSly/44=
  UPLOAD_FOLDER: uploaded_files
  DOWNLOAD_FOLDER: processed_files
  MAX_CONTENT_LENGTH: 40000000
  BUCKET_NAME: "miso-cloud-gr32"
  SECRET_KEY: "xD$F*CV&O0cU"
  SQS_QUEUE_NAME: conversor_queue
smtp:
  SERVER: "172.168.1.252"
  PORT: 1025
  EMAIL: "conversor_miso@conversor.com"
  