name: "PROJECTO - MISO: SOFTWARE CLOUD G32"
aws:
  AWS_ACCESS_KEY_ID: ASIA3GGSDDLFJJ2ENQ5I
  AWS_SECRET_ACCESS_KEY: 9Sb5o2vWS4ZRzQ18hcfvQP0wtP7vBKxh7Q599//6
  AWS_SESSION_TOKEN: FwoGZXIvYXdzEO///////////wEaDMKYcMtWLsE1xUEF9yLLATonVS1y5+blSTFJzB9xyNVUzm0hAR11TdAjBvabLvr+YqGZQ3M03UQOP2N0PiQGihIDZCGFx8DczRPIbyVMApVFary1wdr1ypPcUOZaPwp4nEyXGZZL6I0ZtEj+zDv3LW6DNngnI31qWV8Pi7PtwgwGfSmsrDE9va9/pc3ik/Q0APu5L8SNaJGAy4q92BBXoFHtHkAb8TYRSQaBWBWgr81IQMcYmERW0c6d3MIeHZbLrhBZuKnaHbb4x8WXp0aJyy94ZF1mCiJQTQ7YKJ/aiI0GMi0bE74cOTiPs/t3t6jllIuh/U8Vz/FoQBXJ4ieWPT+6UwyAAe5KcExyx17IHw0=
  UPLOAD_FOLDER: uploaded_files
  DOWNLOAD_FOLDER: processed_files
  MAX_CONTENT_LENGTH: 40000000
  CELERY_BROKER_URL: "redis://172.168.1.119:6379/0"
  CELERY_RESULT_BACKEND: "redis://172.168.1.119:6379/0"
  BUCKET_NAME: "miso-cloud-gr32"
  SECRET_KEY: "xD$F*CV&O0cU"
smtp:
  SERVER: "172.168.1.252"
  PORT: 1025
  EMAIL: "conversor_miso@conversor.com"
  