name: "PROJECTO - MISO: SOFTWARE CLOUD G32"
aws:
  AWS_ACCESS_KEY_ID: ASIA3GGSDDLFJYDUX6E4
  AWS_SECRET_ACCESS_KEY: Fefdb+YsgY8J+3lOSbJFgOuLZftezqFE6HJyyXEO
  AWS_SESSION_TOKEN: FwoGZXIvYXdzEGQaDJmMTnMEEQbGRMgKpiLLAWpfcQnrKyDOVNV+psHb480DReWoZPsLHXRI9M+/boASCSn6X33I05Fhzp0bBCnw3DqhlupcjYgnwpy27nmqwc7ViqOQgyATGxqdZEa/cxv6+1PePFAbeabyAXXh/8rXbjpfzo+sTTkYd2+r0PcAjc2n+dFotNt/rOFaJqKzIJpxmSZfybeokBKOT4cfVDtWyETJw7gzs7Jc6z62WYC92CxVviLYkGTWlYcbES1nHbmuArhMLJ1d4qTnzAA6wzAyMrQ7ACD2GciDNM+LKPys6owGMi1zvETUQfVc1V4E8vThxlIeP1QCiqbyex0B55Ib0Zi67roxPXFv3hJmllNTjmw=
  BUCKET_NAME: 'miso-cloud-gr32'
app-config:
  JWT_SECRET_KEY: ncF!vCivBkAm&Qvg
  PROPAGATE_EXCEPTIONS: True
  UPLOAD_FOLDER: uploaded_files
  DOWNLOAD_FOLDER: processed_files
  MAX_CONTENT_LENGTH: 40000000
  CELERY_BROKER_URL: "redis://172.168.1.119:6379/0"
  CELERY_RESULT_BACKEND: "redis://172.168.1.119:6379/0"
smtp:
  SERVER: "172.168.1.252"
  PORT: 1025
  EMAIL: "conversor_miso@conversor.com"
  