name: "PROJECTO - MISO: SOFTWARE CLOUD G32"
aws:
  AWS_ACCESS_KEY_ID: ASIA3GGSDDLFLNEMLFOB
  AWS_SECRET_ACCESS_KEY: XZuY1blBceBVSryrXk5FpNYD9HK4+d6jBqAnkSTo
  AWS_SESSION_TOKEN: FwoGZXIvYXdzEHEaDBSD3ig214nEHQMDmiLLAaPZXNnF/ZK70exKCsmGLJyN7PAJDdEJexeRuyRHc19BZR2XMuMb9mhvLfrvyTU1M4EPd3Ziuo8LLEgGrqd/A9N7Wf8MCbsKnxqGD4cmSz6abO2t7mClAgTfTO1vfeZ3LonwCOUY9opJccRta7onq2XZVCeFSNl/yoa0Wi9H8ZncR3CS9Y/88Pk/eF1PssjNmKYr3EjX3vnbzSEgsiWHM4GAfAYgGAQOFnmBrDMtQoEIDVu7DGRIDZv69c5aXLd77ycHVae2NdV2wvJEKMezpY0GMi0vpMfhUnNrwr/oI13hD+0j/mgPDdSh4cYv/Ck85Rq9Fg8ciEM3f4XtDPRhuhU=
  UPLOAD_FOLDER: uploaded_files
  DOWNLOAD_FOLDER: processed_files
  MAX_CONTENT_LENGTH: 40000000
  BUCKET_NAME: "miso-cloud-gr32"
  SECRET_KEY: "xD$F*CV&O0cU"
  SQS_QUEUE_NAME: conversor_queue
smtp:
  SERVER: "172.168.1.252"
  PORT: 1025
  EMAIL: "conversor_miso@conversor.com"
  