name: "PROJECTO - MISO: SOFTWARE CLOUD G32"
aws:
  AWS_ACCESS_KEY_ID: ASIA3GGSDDLFCCD5DSOR
  AWS_SECRET_ACCESS_KEY: cgJuzRMW8mzzBfhrxlFbXQsunXupXCFs9JuNLaeV
  AWS_SESSION_TOKEN: FwoGZXIvYXdzEAsaDHyYw3h5EFCuN+118SLLAVPTAFXlyl6D08h/0pPMdA5E6VkNTNC5/5YTmEMEf5vfqddQbN00WZE8/D+Gtda+DMsdP3nBl108wf20gQXiazMN6k9ONAaGH09ZE5Il6prHUU4Hc2z/o6ps9YBhhX9Jj1R9ubAC85eVk7Qn7wg+KP/5hGOfHKm//ctPkOkrkgkLGDPP8SIHCbE9862h6Fl4WCKW8RFa6a1SwaS7vtztOuXktycDc92EGCha3un2t+NxjP+VJImV4ugftt+j5P+D3lA9Lfwfg5rKMRefKLeIj40GMi0tz8d4kzlfDXdsRTTaLIC8IQwdof6kwLNrKe+yEqiK3lgSIX/WEIY1LpUA/IE=
  UPLOAD_FOLDER: uploaded_files
  DOWNLOAD_FOLDER: processed_files
  MAX_CONTENT_LENGTH: 40000000
  BUCKET_NAME: "miso-cloud-gr32"
  SECRET_KEY: "xD$F*CV&O0cU"
  SQS_QUEUE_NAME: conversor_queue
smtp:
  SERVER: "172.168.1.252"
  PORT: 1025
  EMAIL: "conversor_miso@conversor.com"
  