name: "PROJECTO - MISO: SOFTWARE CLOUD G32"
aws:
  AWS_ACCESS_KEY_ID: ASIA3GGSDDLFIBJ2LBXP
  AWS_SECRET_ACCESS_KEY: CFWC8bQNLeXEZUoUJ0/6RmxwDg/yv/Ztk8gx9kZm
  AWS_SESSION_TOKEN: FwoGZXIvYXdzEPL//////////wEaDKeMd8xS/W4XE0UgniLLAdJNwWPOdA2WI7xq3rqoB670bXYV3iWfOX7PtBE2Mh4SHaYptlkgez/yP4WjUFJ42rmpZ9s0N/wwhvrWU28G8AtX5HJWKPUIaw1AJWSVjJIIY+Jsoi6li1DrtymBJvIv92nNNiEyVXssw5dnpYlUxFfLrNcPMoXRuBW6EbquSB0MxvlhAvWZNiu/GsNZ04adMu7Olc/uOkRaEuQ5/qI/CjTKW4tKZNpTQURexYl+GmJRKIijPgS7YbN9L2mRTssadU9Bh9dQSVqVWU8jKL++iY0GMi1tUYwK02K/uV2y6Jv0rHOAO7vFf8rG5IWMWCWg2QB6HCMy/ZQ0CYE4yGIzwgk=
  UPLOAD_FOLDER: uploaded_files
  DOWNLOAD_FOLDER: processed_files
  MAX_CONTENT_LENGTH: 40000000
  CELERY_BROKER_URL: "redis://172.168.1.119:6379/0"
  CELERY_RESULT_BACKEND: "redis://172.168.1.119:6379/0"
  BUCKET_NAME: "miso-cloud-gr32"
  SECRET_KEY: "xD$F*CV&O0cU"
smtp:
  SERVER: "172.168.1.252"
  PORT: 1025
  EMAIL: "conversor_miso@conversor.com"
  