name: "PROJECTO - MISO: SOFTWARE CLOUD G32"
aws:
  AWS_ACCESS_KEY_ID: ASIA3GGSDDLFMACB7XDK
  AWS_SECRET_ACCESS_KEY: xR2xAn34BWqiu4AEa/rYr9PzWShlzKKmjPUj3Z0h
  AWS_SESSION_TOKEN: FwoGZXIvYXdzEPn//////////wEaDBqkH3YifWOgPi+XiSLLAdCQ5Pf+7o7n8ZYiIQg2rvYbK5aQylpmaC3+z6x/S/asq68YErikWjlm0oMnAKjjz6iBo4fp5DT2AF/Wain1NTA0HsqG6lhYTOV++AbcGUCj2e3mmheINhcuYUxtc0EPZE0JPk5vwOCNpFjDDD40mwywqLUVb0uz8+1V6iy4lDoKQFaBhBzPCxT779yZ3b5KH+MNZ0rwhDF6UWHQOMl3/ttgKn+zzPa72zQDzEij0C/k9+WolU+1valx4O8Sm3VPbRhgzLgZLgm6B3olKJWDi40GMi2l0T0na6ai8pwO/ZQExDXGpW4HigRhiCh9XYfPFeUe5xDKIdM1t8Xt830bebA=
  UPLOAD_FOLDER: uploaded_files
  DOWNLOAD_FOLDER: processed_files
  MAX_CONTENT_LENGTH: 40000000
  BUCKET_NAME: "miso-cloud-gr32"
  SECRET_KEY: "xD$F*CV&O0cU"
  SQS_QUEUE_NAME: conversor_queue
smtp:
  SERVER: "172.168.1.252"
  PORT: 1025
  EMAIL: "conversor_miso@conversor.com"
  