name: "PROJECTO - MISO: SOFTWARE CLOUD G32"
aws:
  AWS_ACCESS_KEY_ID: ASIA3GGSDDLFAXRBMV7Q
  AWS_SECRET_ACCESS_KEY: iNNA2lVhc8LsYQWdf6LnQ7/5/pvys45EK9Lwhsno
  AWS_SESSION_TOKEN: FwoGZXIvYXdzEG8aDCcCNQAzGJWNStQjmCLLARHyFmS4beqeAtL0+sUdn7iFY7dWY2O+5GrSq85MFcA9Fj2Qtu3EiAKdsHKuyxLmme5oinzU5w+tdbFlE/8mwgDop4RsnwUWWizdCSYqeeKIfGon3fUiVjpQJpD/9UDAOT1eWpOa3Nq5h/cyMfw0tzF2TnYYZDdqWS2XssseOj0JWSC4HRr5OOiFRxuI2FtOLFp2896L7ATye+uyC/keBYg9zgPlJdScCMOUadAia/UUbhM1SwDV2kf4sFI0npfm8HhsRZrtbln0cfJqKP6CpY0GMi1YyEmg128QJuDdragnmCx74MNcG7D5SHQLFWm+ejK17kRl08u7jIS9fYPd3mY=
  UPLOAD_FOLDER: uploaded_files
  DOWNLOAD_FOLDER: processed_files
  MAX_CONTENT_LENGTH: 40000000
  BUCKET_NAME: "miso-cloud-gr32"
  SECRET_KEY: "xD$F*CV&O0cU"
  SQS_QUEUE_NAME: conversor_queue
smtp:
  SERVER: "172.168.1.252"
  PORT: 1025
  EMAIL: "conversor_miso@conversor.com"
  