version: "3.1"

services:
  api:
    build: ../flaskr
    restart: always
    ports:
      - 6379:6379
      - 5432:5432
    command: ["./start-flask.sh"]
  server:
    build: ../server
    restart: always
    depends_on:
      - api
    ports:
      - 5000:80
volumes:
  db_info: {}