name: "PROJECTO - MISO: SOFTWARE CLOUD G32"
aws:
  AWS_ACCESS_KEY_ID: ASIA3GGSDDLFKCJOVPGF
  AWS_SECRET_ACCESS_KEY: V4PY/rIHRjQNwhvd5DNSO2EdIF0lVRySgfR0PInE
  AWS_SESSION_TOKEN: FwoGZXIvYXdzEFAaDIoFwY7k1Fkm9+UCySLLAVMChaZd1XABKIfQksQ18KeWL7RxfCCY9RdLXcuPC1IcLxuLd5q3BilzTzoLG+7WMiXw48ZDQltyZeW/SZw7KJOoDqI74vq835IgKJc76vlNeLQWDkWl9sshiErUfkGs3Cx3lJgubwOi99n9soo6vtCYYOpYVvBFmGSfs16NgJ7mCfXQy+ebojq7hx2aVGpEFnIrn+LhN+uNSIpRwybYUMcLTACIGQCqeQJLdsrcl2CP/jNEE7Bbh8nD+fMTiS07m4WUgEVEAeB2OLZsKIDk5YwGMi3dTH5szupG+k3+aIEhIx5uXT7QKWnT6Remx6cTobKS3x8WXo0+/dx+z72r5b0=
  BUCKET_NAME: 'miso-cloud-gr32'
app-config:
  JWT_SECRET_KEY: ncF!vCivBkAm&Qvg
  PROPAGATE_EXCEPTIONS: True
  UPLOAD_FOLDER: uploaded_files
  DOWNLOAD_FOLDER: processed_files
  MAX_CONTENT_LENGTH: 40000000
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
smtp:
  SERVER: "172.168.1.252"
  PORT: 1025
  EMAIL: "conversor_miso@conversor.com"
  