name: "PROJECTO - MISO: SOFTWARE CLOUD G32"
aws:
  AWS_ACCESS_KEY_ID: ASIA3GGSDDLFJRZHOZWH
  AWS_SECRET_ACCESS_KEY: 9JYEYUUIwthfZkyLDMSmcLF1LAkV1ZZyYAFIQ+1V
  AWS_SESSION_TOKEN: FwoGZXIvYXdzEFMaDBo99I0v9JcgAvGHhyLLAWgt5OWcf1PwgS4YVWGbqrJT10lGWeKXiTEqAcLqisUK56zI5ty378ZKyygFLu7VcV9waCPDl3cUMovkISi/85hf/3Dxap5YiomIXN1QumiEHoEXiVQmXf9pwrq24TYW1f/gAK2iMW6QHBz61+mFuj1EK+youqIwDis1E/IUfMTmI4ltOJHdPWlU/Jd8z3/qWKB6sJv/bVv3ACXNtgkvL7cHKMGTV5hjAoLbIgstEmQ8BwZBpNw3PlRi8eEt1Y+5/7aJLauHwqXMs4jkKOS65owGMi0zZDM29IsjNfEuiTEKm+dXKFWCxyDm3l0xK5bCP6Lr+BWjPbIIHpXXzdWRFew=
  BUCKET_NAME: 'miso-cloud-gr32'
app-config:
  JWT_SECRET_KEY: ncF!vCivBkAm&Qvg
  PROPAGATE_EXCEPTIONS: True
  UPLOAD_FOLDER: uploaded_files
  DOWNLOAD_FOLDER: processed_files
  MAX_CONTENT_LENGTH: 40000000
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
smtp:
  SERVER: "172.168.1.252"
  PORT: 1025
  EMAIL: "conversor_miso@conversor.com"
  